// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHgiCcuBS2Ad95zqPEEZHPxkN0Op0YgHo',
    appId: '1:669293514358:android:fe7beb39abe5a329095957',
    messagingSenderId: '669293514358',
    projectId: 'livescorex-7e4f6',
    storageBucket: 'livescorex-7e4f6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPN4bKiw5XGwVuI9LnqUba57VsKgcxZTg',
    appId: '1:669293514358:web:2cffac5260eb5ec7095957',
    messagingSenderId: '669293514358',
    projectId: 'livescorex-7e4f6',
    authDomain: 'livescorex-7e4f6.firebaseapp.com',
    storageBucket: 'livescorex-7e4f6.firebasestorage.app',
    measurementId: 'G-1ZCXFXJJHB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQrg24M-BgAaR68uCGWiew9YeB8nOakh8',
    appId: '1:669293514358:ios:99ef9f479316c28c095957',
    messagingSenderId: '669293514358',
    projectId: 'livescorex-7e4f6',
    storageBucket: 'livescorex-7e4f6.firebasestorage.app',
    iosBundleId: 'com.livescorex',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQrg24M-BgAaR68uCGWiew9YeB8nOakh8',
    appId: '1:669293514358:ios:99ef9f479316c28c095957',
    messagingSenderId: '669293514358',
    projectId: 'livescorex-7e4f6',
    storageBucket: 'livescorex-7e4f6.firebasestorage.app',
    iosBundleId: 'com.livescorex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPN4bKiw5XGwVuI9LnqUba57VsKgcxZTg',
    appId: '1:669293514358:web:703434a929a633ce095957',
    messagingSenderId: '669293514358',
    projectId: 'livescorex-7e4f6',
    authDomain: 'livescorex-7e4f6.firebaseapp.com',
    storageBucket: 'livescorex-7e4f6.firebasestorage.app',
    measurementId: 'G-ZYCNJRDT8S',
  );

}