// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_qBtcVZB9ALB_l22Aiki-0f9yVVvmHQ',
    appId: '1:363163883200:android:bc210c4b667ba39e57ff25',
    messagingSenderId: '363163883200',
    projectId: 'pulsescore-a8722',
    storageBucket: 'pulsescore-a8722.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMWt_05l2Kx3Ab-DdhDYqhbGx2oMG0N6c',
    appId: '1:363163883200:web:207f27ccf05bfffb57ff25',
    messagingSenderId: '363163883200',
    projectId: 'pulsescore-a8722',
    authDomain: 'pulsescore-a8722.firebaseapp.com',
    storageBucket: 'pulsescore-a8722.firebasestorage.app',
    measurementId: 'G-GFG7HZYVSP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK6r_M5N9kN3cfIbugWkzN1xKakjOvI24',
    appId: '1:363163883200:ios:04df9eb1e19253ad57ff25',
    messagingSenderId: '363163883200',
    projectId: 'pulsescore-a8722',
    storageBucket: 'pulsescore-a8722.firebasestorage.app',
    iosBundleId: 'com.livefooltballscore',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK6r_M5N9kN3cfIbugWkzN1xKakjOvI24',
    appId: '1:363163883200:ios:04df9eb1e19253ad57ff25',
    messagingSenderId: '363163883200',
    projectId: 'pulsescore-a8722',
    storageBucket: 'pulsescore-a8722.firebasestorage.app',
    iosBundleId: 'com.livefooltballscore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMWt_05l2Kx3Ab-DdhDYqhbGx2oMG0N6c',
    appId: '1:363163883200:web:27d0ea29f179246757ff25',
    messagingSenderId: '363163883200',
    projectId: 'pulsescore-a8722',
    authDomain: 'pulsescore-a8722.firebaseapp.com',
    storageBucket: 'pulsescore-a8722.firebasestorage.app',
    measurementId: 'G-17V2SNJNYG',
  );
}
